# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Zip Release
  # You may pin to the exact commit or the version.
  # uses: TheDoctor0/zip-release@591e9b128012d3328db6043d0d0266c3ac27f9b5
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: Alerk.zip
          path: .
          directory: .
          exclusions: README.md
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Alerk.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
